### ISSUE TITLE
Manu 1 - Profile(Main Company, Client Company, Sub Client Company)

### ISSUE THREAD

**Issue by sadishchandru** [sadishchandru/billplex#2]
Sub Menu - 
 - **Main Company** [Search Form Design](https://drive.google.com/file/d/1W4KKK_eDjsdtXjeoAKOCvK-V2zVdO_b3/view?usp=share_link), [Input Form Design](https://drive.google.com/file/d/1GBygOGRC53Ag6RJsORs6sUCYiaRT7U4d/view?usp=share_link)

-  _Main Company Information_ - Company Code, Company Name, Office Address, State, Pin Code, Office Phone, Starting Date, Business Nature (Manufacture, Job Work, Traders, Others), Email, Website, PFCode, ESI Code, Factory Act No., TIN No, CST NO, SSI No, TAN No., License No., 

- _Authorized Person Information_ - Name, Father / Husband Name, Gender (Male, Female), Address, State, Pin code, Phone, Blood Group, DOB, Email, Mobile, Pan No.

- _Main Company Bank Details_ - Main Company, Bank Name, Bank A/C No., Address, Branch Name, IFS Code

 - **Client Company** [Search Form Design](https://drive.google.com/file/d/11fGHBRs26Nn1aJm15WCv9T8YFPkn_EL3/view?usp=share_link), [Input Form Design](https://drive.google.com/file/d/1LpU4TYUaKgPWcHHEfN3yoVRO_X_2uZiw/view?usp=share_link)
 - _Client Company Info_. - Main Company Name, Director, Company Code, Company Name, Office Address, state, Pin, Business Nature – (Manufacturer, job work, traders, others), phone no, mail, website, PF Type – (Category 1, Category 2), PF Code, PF Date, ESI Code, ESI Date, Factory Act No, TIN No, CST No, GST, SSI No, PAN, TAN, License No
 

- _Authorized Person Information_ - Name, Father / Husband Name, Gender (Male ,Female), Address, State, Pin code, Phone, Blood Group, DOB, Email, Mobile, Pan No.

- _Client Company Bank Details_ - Main Company, Client Company, Bank Name, Bank A/C No., Address, Branch Name, IFS Code

 - **Sub Client Company** [Search Form Design](https://drive.google.com/file/d/1AfSuBdAXrI5LzAl24YwSws0uVvqPqNE2/view?usp=share_link), [Input Form Design](https://drive.google.com/file/d/1ay4iejOT-Yq6y6MEEfX0JZv9uU7TC0ib/view?usp=share_link)
 - _Sub Client Company Info._ - Main Company Name, Director, Company Code, Company Name, Sub Company Code, Sub Company Name, Office Address, state, Pin, Business Nature – (Manufacturer, job work, traders, others), phone no, mail, website, PF Type – (Category 1, Category 2), PF Code, PF Date, ESI Code, ESI Date, Factory Act No, TIN No, CST No, GST, SSI No, PAN, TAN, License No
 

- _Authorized Person Information_ - Name, Father / Husband Name, Gender (Male,Female), Address, State, Pincode, Phone, Blood Group, DOB, Email, Mobile, Pan No.

- _Sub Client Company Bank Details_ - Client Company, Sub Client Company, Bank Name, Bank A/C No., Address, Branch Name, IFS Code.

**Comment by SrinivasanTwilight** [comment]
Under Profile Module

**Search Form Design** 
1. Main Company-> Done
2. Client Company -> Done
3. Sub Client Company -> Done

**Input Form Design**
1. Main Company-> Done
2. Client Company -> InProgress
3. Sub Client Company -> InProgress

DB Side Task:

1. Created DB name as Billplex
2. Created CompanyProfile table and its column
